name: Publish to Nuget

on:
  push:
    branches:
      - main # Default release branch
jobs:  
  publish:
    runs-on: ubuntu-20.04
    env:
      AssentNonInteractive: true
    steps:
      - name: Print new build number
        run: echo "Build number is ${env:GITHUB_RUN_NUMBER}"
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run git init
        run: git init
      - name: 'Setup .NET Core SDK 3.1.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/main/CsharpDotNet2/SigParser/SigParser.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: SigParser
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: 1.0.${{GITHUB_RUN_NUMBER}}

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_SECRET}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
      
      
          
  

