name: Publish to Nuget

on:
  push:
    branches:
      - main # Default release branch
jobs:  
  publish:
    runs-on: ubuntu-20.04
    env:
      AssentNonInteractive: true
    steps:
      - name: Print new build number
        run: echo "Build number is ${env:GITHUB_RUN_NUMBER} Double Curlies ${env:GITHUB_RUN_NUMBER}"
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run git init
        run: git init
      - name: 'Setup .NET Core SDK 3.1.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Create Nuget package SigParser.dll and publish
        if: success()
        run: |
          dotnet pack src/main/CsharpDotNet2/SigParser/SigParser.csproj -p:IncludeSymbols=false -p:SymbolPackageFormat=snupkg --configuration Release -p:PackageVersion=3.0.${env:GITHUB_RUN_NUMBER}
          dotnet nuget push src/main/CsharpDotNet2/SigParser/bin/Release/SigParser.3.0.${env:GITHUB_RUN_NUMBER}.nupkg --api-key "${{ secrets.NUGET_SECRET }}"  
      
      
      
          
  

